sonar.organization=sgac-gestaoatividadecomplementarorg
sonar.projectKey=sgac-gestaoatividadecomplementarorg_gestaoatividadecomplementarorg-frontend
sonar.projectName=gestaoatividadecomplementarorg-frontend
sonar.host.url=https://sonarcloud.io

# Fontes e Testes do Angular
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

# Relatório LCOV gerado pelos testes
sonar.javascript.lcov.reportPaths=coverage/sonar/lcov.info