name: Render service manter ativo

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:

      - name: Check Frontend
        run: |
          echo "Checking frontend..."

          curl \
            --fail \
            --silent \
            --show-error \
            --max-time 30 \
            https://gestaoatividadescomplementares.onrender.com/

          echo "Frontend esta UP."

      - name: Check Backend
        run: |
          echo "Checking backend..."

          curl \
            --fail \
            --silent \
            --show-error \
            --max-time 30 \
            https://gestaoatividadescomplementares-backend.onrender.com/api/v1/health

          echo "Backend esta UP."

      - name: Check Database
        run: |
          echo "Checking database..."

          curl \
            --fail \
            --silent \
            --show-error \
            --max-time 30 \
            https://gestaoatividadescomplementares-backend.onrender.com/api/v1/health/database

          echo "banco de dados está UP."
